export const formStyles = {
    container: "min-h-screen flex items-center justify-center bg-gradient-to-br from-indigo-600 via-purple-600 to-pink-500 p-4 font-sans",
    card: "w-full max-w-md bg-white/95 backdrop-blur-xl p-8 rounded-3xl shadow-2xl transform transition-all hover:shadow-indigo-500/20",
    logoContainer: "flex justify-center mb-8",
    logo: "h-16 w-auto drop-shadow-md hover:scale-110 transition-transform duration-300",
    title: "text-3xl font-extrabold text-center text-gray-800 mb-2 tracking-tight",
    subtitle: "text-gray-500 text-center mb-8 text-sm font-medium",
    form: "space-y-6",
    inputGroup: "relative group",
    label: "block text-sm font-semibold text-gray-700 mb-1 ml-1 group-focus-within:text-indigo-600 transition-colors",
    inputWrapper: "relative",
    inputIconContainer: "absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none text-gray-400 group-focus-within:text-indigo-500 transition-colors",
    inputIcon: "h-5 w-5",
    input: "w-full pl-10 pr-4 py-3 border border-gray-200 rounded-xl bg-gray-50 focus:bg-white focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:border-transparent transition-all duration-200 ease-in-out shadow-sm text-gray-700 placeholder-gray-400",
    rememberContainer: "flex items-center justify-between",
    checkboxContainer: "flex items-center space-x-2 cursor-pointer group",
    checkboxWrapper: "relative flex items-center",
    checkbox: "peer h-4 w-4 text-indigo-600 border-gray-300 rounded focus:ring-indigo-500 cursor-pointer transition-colors",
    rememberText: "text-sm text-gray-600 group-hover:text-gray-800 transition-colors",
    forgotPassword: "text-sm font-medium text-indigo-600 hover:text-indigo-500 hover:underline transition-colors",
    button: "w-full bg-gradient-to-r from-indigo-600 to-blue-600 text-white font-bold py-3.5 rounded-xl hover:from-indigo-700 hover:to-blue-700 focus:outline-none focus:ring-4 focus:ring-indigo-300 shadow-lg shadow-indigo-500/30 transform hover:-translate-y-0.5 transition-all duration-200 flex items-center justify-center gap-2",
    buttonIcon: "h-5 w-5",
    dividerContainer: "relative mt-8",
    dividerLine: "absolute inset-0 flex items-center",
    dividerLineInner: "w-full border-t border-gray-200",
    dividerTextContainer: "relative flex justify-center text-sm",
    dividerText: "px-4 bg-white text-gray-500 font-medium",
    socialButtons: "mt-6 flex gap-4",
    googleButton: "flex-1 flex justify-center items-center gap-2 py-2.5 border border-gray-200 rounded-xl hover:bg-gray-50 hover:border-gray-300 transition-all duration-200 text-sm font-medium text-gray-700 shadow-sm",
    registerText: "mt-8 text-center text-sm text-gray-500",
    registerLink: "font-semibold text-indigo-600 hover:text-indigo-500 hover:underline transition-colors",
    copyright: "mt-6 text-center text-xs text-gray-400"
};
